FROM heroku/heroku:16
MAINTAINER hone

# need these deps to build mupdf
RUN apt update && apt install -y \
  libgl1-mesa-dev \
  mesa-common-dev \
  pkg-config \
  xorg-dev

# setup workspace
RUN rm -rf /tmp/workspace
RUN mkdir -p /tmp/workspace

# output dir is mounted

ADD build.sh /tmp/build.sh
CMD ["sh", "/tmp/build.sh", "/tmp/workspace", "/tmp/output"]
